library(jsonlite)


data <- fromJSON('data/result.json')

class(data)
class(data$graph)
data$graph
View(advertiser_campaigns)
unique(json_data[["nodes"]][["color"]])
unique(data[["nodes"]][["color"]])
which( data[["nodes"]][["color"]] == "blue")
which( data[["nodes"]][["color"]] == "red")
unique(data[["nodes"]][["type"]])
which( data[["nodes"]][["type"]] == "TRUE")
which( data[["nodes"]][["type"]] == "False")
which( data[["nodes"]][["type"]] == "FALSE")
unique(data[["nodes"]][["type"]])
which( data[["nodes"]][["type"]] == "FALSE")
fdata = which( data[["nodes"]][["type"]] == "FALSE")
tdata = which( data[["nodes"]][["type"]] == "TRUE")
length(fdata)
length(tdata)
rdata = which( data[["nodes"]][["color"]] == "red")
bdata = which( data[["nodes"]][["color"]] == "blue")
length(rdata)
length(bdata)
unique(json_data[["nodes"]][["_igraph_index"]])
unique(data[["nodes"]][["_igraph_index"]])
nodeindex = unique(data[["nodes"]][["_igraph_index"]])
length(nodeindex)
linkindex = unique(data[["links"]][["_igraph_index"]])
length(linkindex)
unique(data[["links"]][["source"]])
unique(data[["links"]][["target"]])
sorlink = unique(data[["links"]][["source"]])
tarlink = unique(data[["links"]][["target"]])
length(sorlink)
length(tarlink)
length(nodeindex)
length(tarlink)
length(fdata)
length(tdata)
class(data['nodes'])
class(data['nodes'][0])
class(data['nodes'])
class(data$nodes)
nodes = data$nodes
link_data <- data$links
node_data <- data$nodes
class(node_data)
class(link_data)
node_data.head()
head(node_data)
colnames(link_data)
rownames(link_data)
write_csv(link_data, "links.csv")
write_csv(node_data, "node.csv")
class(link_data$source)
class(link_data$target)
class(link_data$key)
class(link_data$`_igraph_index`)
class(node_data$`_igraph_index`)
class(node_data$name)
class(node_data$type)
class(node_data$color)
class(node_data$id)